### ISSUE TITLE
idea using CallerMemberNameAttribute 

### ISSUE THREAD

**Issue by netpyoung** [if1live/unity-utility#1]
이런것도 가능할것같네요!

http://www.sysnet.pe.kr/Default.aspx?mode=2&sub=0&detail=1&pageno=0&wid=10890&rssMode=1&wtype=0

before
```cs
    [AssetName("twitter_dark.png")]
    public Texture2D icon;
```

after
```cs
    [AssetPNG]
    public Texture2D twitter_dark;
```

**Comment by goyusia** [comment]
괜찮은 아이디어지만 2가지 문제가 생길거같네요.

1. 에셋 파일명 건드릴때 변수명 바뀌면서 코드가 잔뜩 수정되는 문제

2. 파일명에는 쓸수있지만 변수명에는 못 쓰는 문자때뭄에 `foo-bar.png`인데 변수명은 `foo_bar`가 된다거나

**Comment by goyusia** [comment]
@netpyoung https://github.com/if1live/unity-utility/commit/366428337075737a138e416089ce8a3c97f38b36

```csharp
public class AssetVariableConnectSample : MonoBehaviour {
	[AssetVariable("png")]
	public Texture2D twitter_dark;

	[AssetVariable(".png")]
	public Texture2D icons_set_black;

	[AssetVariable]
	public AudioClip Click_Mechanical_00;
}
```
